### ISSUE TITLE
Django admin's list view generates wrong change links (missing id)

### ISSUE THREAD

**Issue by hetsch** [nesdis/djongo#34]
#### One line description of the issue
Django admin list view is missing the id (pk) of the objects

#### Python script
If using your example from the homepage with django's admin app, a BlogPost object can be sucessfully created, but once you are in the list view and try to edit the items or hover over the links, the change links are all missing the specific ids (e.g. `http://localhost/admin/xxx/blogpost/None/change/`). 

```python
# in models.py
from djongo import models
from djongo.models import forms

class BlogContent(models.Model):
    comment = models.CharField(max_length=100)
    author = models.CharField(max_length=100)

    class Meta:
        abstract = True

class BlogContentForm(forms.ModelForm):
    class Meta:
        model = BlogContent
        fields = (
            'comment', 'author'
        )

class BlogPost(models.Model):
    h1 = models.CharField(max_length=100)
    content = models.EmbeddedModelField(
        model_container=BlogContent,
        model_form=BlogContentForm
    )

# in admin.py
admin.site.register(BlogPost)
```

I use:
Django 1.11.8
djongo (git master)
Mongodb 3.6

**Comment by nesdis** [comment]
Only the first time you need to run migrations on you app so the auto-id field gets generated properly

**Comment by hetsch** [comment]
Hmm... It seems that the initial migrations are not created if called `manage.py makemigrations`. Starting from a clean django project and the following Models in `models.py`:

```
from djongo import models
from djongo.models import forms


class BlogContent(models.Model):
    comment = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
	
    class Meta:
        abstract = True


class BlogContentForm(forms.ModelForm):

    class Meta:
        model = BlogContent
        fields = (
            'comment', 'author'
        )


class BlogPost(models.Model):
    h1 = models.CharField(max_length=100)
    content = models.EmbeddedModelField(
        model_container=BlogContent,
        model_form=BlogContentForm
    )
```

calling

```
C:\Users\xxx\Downloads\tmp\foo>manage.py makemigrations
No changes detected

C:\Users\xxx\Downloads\tmp\foo>manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying sessions.0001_initial... OK
```
Only django default migrations are created

**Comment by nesdis** [comment]
Try manage.py makemigrations (app_name)

On 22-Dec-2017 3:37 PM, "hetsch" <notifications@github.com> wrote:

Hmm... It seems that the initial migrations are not created if called manage.py
makemigrations. Starting from a clean django project and the following
Models in models.py:

from djongo import models
from djongo.models import forms


class BlogContent(models.Model):
    comment = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
	
    class Meta:
        abstract = True


class BlogContentForm(forms.ModelForm):

    class Meta:
        model = BlogContent
        fields = (
            'comment', 'author'
        )


class BlogPost(models.Model):
    h1 = models.CharField(max_length=100)
    content = models.EmbeddedModelField(
        model_container=BlogContent,
        model_form=BlogContentForm
    )

calling

C:\Users\xxx\Downloads\tmp\foo>manage.py makemigrations
No changes detected

C:\Users\xxx\Downloads\tmp\foo>manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying sessions.0001_initial... OK

Only django default migrations are created

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/nesdis/djongo/issues/34#issuecomment-353566074>, or mute
the thread

**Comment by hetsch** [comment]
Please excuse, was a stupid mistake of mine. Forgot to add app to INSTALLED_APPS. The first issue might have to do with the fact that I have multiple databases Postgres and MongoDB, and I have to adapt my database router. Have you ever tried to use djongo in a multi-DB environement, where the default database is for e.g. Postgres?

**Comment by hetsch** [comment]
@nesdis I'm closing this because it was a bug in my database router allow_migrations method. Sorry for bugging you with this.
