### ISSUE TITLE
How can we insert  the dictionary(json)  in mongodb ?

### ISSUE THREAD

**Issue by ravinarayansingh** [nesdis/djongo#37]
#### 
apps/models.py
```
data={"name":"xyz","age":12}
year=2017
month=10
class TestModel(models.Model):
    year = models.IntegerField()
    month = models.IntegerField()
    customer = "In this feild i want to store above dictonary"

after having EmbeddedDictField  as type  model will be 
class TestModel(models.Model):
    year = models.IntegerField()
    month = models.IntegerField()
    customer = models.EmbeddedDictField(model_container=dict)
```
 djongo/djongo/models.py
we need to add below  class in   djongo/djongo/models.py
```
djongo/djongo/models.py
class EmbeddedDictField(Field):
    def __init__(self,
                 model_container: typing.Type[dict],
                 model_form_class: typing.Type[forms.ModelForm] = None,
                 model_form_kwargs: dict = None,
                 *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.model_container = model_container
        self.model_form_class = model_form_class
        self.null = True
        self.instance = None

        if model_form_kwargs is None:
            model_form_kwargs = {}
        self.model_form_kwargs = model_form_kwargs

    def deconstruct(self):
        name, path, args, kwargs = super().deconstruct()
        kwargs['model_container'] = self.model_container
        if self.model_form_class is not None:
            kwargs['model_form_class'] = self.model_form_class
        return name, path, args, kwargs

    def pre_save(self, model_instance, add):
        value = getattr(model_instance, self.attname)
        # print(value)
        ret_val = {}
        # for fld in value._meta.get_fields():
        #     if not useful_field(fld):
        #         continue
        #
        #     fld_value = getattr(value, fld.attname)
        # ret_val[ self.attname] = fld.get_db_prep_value(value, None, False)
        ret_val[self.attname] = self.get_db_prep_value(value, None, False)
        return ret_val

    def get_db_prep_value(self, value, connection=None, prepared=False):
        if isinstance(value, dict):
            return value

        if not isinstance(value, Model):
            raise TypeError('Object must be of type Model')

        mdl_ob = {}
        for fld in value._meta.get_fields():
            if not useful_field(fld):
                continue
            fld_value = getattr(value, fld.attname)
            mdl_ob[fld.attname] = fld.get_db_prep_value(fld_value, connection, prepared)

        return mdl_ob

    def from_db_value(self, value, expression, connection, context):
        return self.to_python(value)
```

so that we can create the model
tree = TestModel(year=year,month=month,customer =data)
tree.save()
#### Traceback
Note: data is dyanamic so you cant create a model

**Comment by nesdis** [comment]
Hi @ravinarayansingh

That's a good question.

I request you to copy and paste the question on stackoverflow.

I have noticed many questions which have been closed are asked again.
Documentation for this package can nicely exist on stackoverflow. And will
help lot of other audience.

Whats better you stackoverflow contributions get highly  scored!

Do you think you can paste a link to the question here? I would gladly
answers the pros and cons of ur approach.

Thanks



On 29-Dec-2017 12:35 PM, "ravinarayansingh" <notifications@github.com>
wrote:

I want to insert the dictionary as the value of the model field. For this,
my suggestion is we should have EmbeddedDictField like EmbeddedModelField.
I have tried this and it worked. models.py

data={"name":"xyz","age":12}
year=2017
month=10
class TestModel(models.Model):
    year = models.IntegerField()
    month = models.IntegerField()
    customer = "In this feild i want to store above dictonary"


so that we can create the model
tree = TestModel(year=year,month=month,customer =data)
tree.save()
Traceback

Note: data is dyanamic so you cant create a model

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nesdis/djongo/issues/37>, or mute the thread

**Comment by nesdis** [comment]
Hi the issue with storing a field as a dict is that Django Admin will not work on it. Which is perhaps the biggest drawback. Underneath every model is actually a dict. But by giving it a model representation you make the model 'reuasble' and 'extendable' via inheritance.  If you don't need admin and forms in your project use a dict. Because internally i am converting the model to a dict and storing it.

**Comment by ravinarayansingh** [comment]
sure you can find the link below
https://stackoverflow.com/questions/48020463/how-can-we-insert-dictionaryjson-in-mongodb-with-django-using-djongo-library

**Comment by nesdis** [comment]
If you write documentation for dictField with similar examples to embeddedModel i will merge this into the main branch. Just make sure the naming of different variables follows similar convention.

The documentation for dict field can be added to the doc folder.
