### ISSUE TITLE
tests are slow

### ISSUE THREAD

**Issue by aryaniyaps** [nesdis/djongo#553]
#### description of the issue
tests are slow on mongoDB when compared to other sql backends (probably because mongoDB doesn't support transactions and collections are created and destroyed between every test).

I have 33 tests in my test suite. It took around 5 seconds to run every test (with postgres as the backend).
Switching to mongoDB, this takes well more than 25 seconds.

Is there any way to optimize tests to make it faster with mongoDB?
btw, thanks for maintaining this great library!

#### Example test suite run
```commandline
> python manage.py test --keepdb
Using existing test database for alias 'default'...
This version of djongo does not support "NULL, NOT NULL column validation check" fully. Visit https://nesdis.github.io/djongo/support/
This version of djongo does not support "schema validation using CONSTRAINT" fully. Visit https://nesdis.github.io/djongo/support/
This version of djongo does not support "COLUMN DROP NOT NULL " fully. Visit https://nesdis.github.io/djongo/support/
This version of djongo does not support "DROP CASCADE" fully. Visit https://nesdis.github.io/djongo/support/
This version of djongo does not support "schema validation using KEY" fully. Visit https://nesdis.github.io/djongo/support/
This version of djongo does not support "schema validation using REFERENCES" fully. Visit https://nesdis.github.io/djongo/support/
System check identified no issues (0 silenced).
.................................
----------------------------------------------------------------------
Ran 33 tests in 26.311s

OK
Preserving test database for alias 'default'...
```
I am using djongo version 1.3.4.

**Comment by Miando** [comment]
Hi, @aryan340. The same for me. Did you find some solution?

**Comment by aryan340** [comment]
I didnt find a solution, unfortunately. But that's probably because django doesnt support and doesnt need to support non-relational databases. This library is a connector for the underlying *relational* mapper, so there is no way to alter the default behaviour (enclosing tests within transactions and creating tables for every test case). While the django orm might be powerful, it is limiting in these kind of ways. (There is no native support for mongodb)
I would suggest that you use flask instead if you need to use nosql with python. Flask has no orm support out of the box, so you are free to use the official mongodb orm for python. This is what I did :)
