### ISSUE TITLE
Error when added new model field

### ISSUE THREAD

**Issue by miguelwon** [nesdis/djongo#86]
I changed my models by adding a new `Textfield` to `Entry` model (called `titlesents`). Made the usual makemigrations followed by migrate and then ran a simple populate style script just to check if everything still ok. 

#### Python script
```python
import django,os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "mysite.settings")
django.setup()

from arquivo.models import Entry

all_entries = Entry.objects.all().order_by('-pub_date')
for obj_entry in all_entries:
    print(obj_entry.pub_date)
    try:
        title = obj_entry.title
        obj_entry.title_sents ='teste'
        obj_entry.save()

    except json.decoder.JSONDecodeError:
        print(obj_entry.title,obj_entry.url)
        print("")

    break
```

#### Traceback
```
    File "/home/mwon/arquivopage/venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 262, in _align_results
    ret.append(doc[selected.column])
KeyError: 'titlesents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "textsearchcalc.py", line 47, in <module>
    for obj_entry in all_entries:
  File "/home/mwon/arquivopage/venv/lib/python3.6/site-packages/django/db/models/query.py", line 272, in __iter__
    self._fetch_all()
  File "/home/mwon/arquivopage/venv/lib/python3.6/site-packages/django/db/models/query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/mwon/arquivopage/venv/lib/python3.6/site-packages/django/db/models/query.py", line 62, in __iter__
    for row in compiler.results_iter(results):
  File "/home/mwon/arquivopage/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1005, in apply_converters
    for row in map(list, rows):
  File "/home/mwon/arquivopage/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1460, in cursor_iter
    for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
  File "/home/mwon/arquivopage/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1460, in <lambda>
    for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
  File "/home/mwon/arquivopage/venv/lib/python3.6/site-packages/django/db/utils.py", line 96, in inner
    return func(*args, **kwargs)
  File "/home/mwon/arquivopage/venv/lib/python3.6/site-packages/djongo/cursor.py", line 59, in fetchmany
    ret.append(self.result.next())
  File "/home/mwon/arquivopage/venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 448, in __next__
    return next(self._result_generator)
  File "/home/mwon/arquivopage/venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 454, in __iter__
    yield from iter(self._query)
  File "/home/mwon/arquivopage/venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 169, in __iter__
    yield self._align_results(doc)
  File "/home/mwon/arquivopage/venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 265, in _align_results
    raise MigrationError(selected.column)
djongo.sql2mongo.MigrationError: titlesents
```

**Comment by nesdis** [comment]
Hi @miguelwon 

The error is a migration error. When you add a new field, the previous entries without the field need to be manually set as NULL. That is the cause of this exception.

**Comment by christopher-wiko** [comment]
But this is one advantage of NoSQL: to be able to add a new field, without update the entire collection ?

**Comment by bachinblack** [comment]
Hi,
I have the same problem, but with an empty database and only my initial migration.
Therefore, it can't be a problem with retrocompatibility.
I looked at the code and saw that `connection_properties.enforce_schema = True` was the culprit.
I set it to `False` in the Query contructor and it worked without any problem.

of course, I'm not supposed to edit your code, and by solving MY problem, I may have created a lot more.

But since it worked without any error, I think it is a bug.

**Comment by nesdis** [comment]
> But this is one advantage of NoSQL: to be able to add a new field, without update the entire collection ?
@christopher-wiko 
You need to apply enforce schema = FALSE, if you do not want schema checks in your code

**Comment by SkullEnemyX** [comment]
Man the problem is not solved, where should we change the enforce schema??? and why is this error occuring???

**Comment by SkullEnemyX** [comment]
Can you give a proper example of how to make a proper model with ArrayModelField because it is causing so much problem. Also, the documentation of your whole djongo project is really bad...please put more efforts in maintaining it because without knowing the amount of error that might occur using the djongo library, when one jumps in..it is really difficult to shift back so please help. Thank you much in advanced. We don't know which part of your code works how so please even while solving an issue be more discriptive. I mean how the fuck am I supposed to know where to change the enforce schema or how to solve the problem without touching your code. I am really frustated by the migration error and cant seem to solve it at all. Please , the deadline of my project is near and solving djongo's issue is eating up all my time. Please document properly. I beg you man. No offence at all and thumbs up for the great job you have done till now but more efforts needs to be put or either collaborate with other open source developers to maintain djongo( a great library with a lot of unclarity and bugs)

**Comment by bachinblack** [comment]
Hi,

Here is how I disable ENFORCE_SCHEMA:
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
    },
    'shifts_db': {
        'ENGINE': 'djongo',
        'ENFORCE_SCHEMA': False,
    }
}
```

It's been some time since I've done it so I don't remember exactly how I fixed this problem but disabling ENFORCE_SCHEMA may be enough.

Note that you can also log directly to your mongo db and add the required field to every documents. Then djongo will work again. I suppose ENFORCE_SCHEMA=True should fill these fields by itself but it doesn't seem to.

Anyway, disabling it looks like a good way but then you should frequently check that your docs contain the fields you are looking for (because they won't necessarily).

**Comment by endersonmenezes** [comment]
> Hi,
> 
> Here is how I disable ENFORCE_SCHEMA:
> 
> ```
> DATABASES = {
>     'default': {
>         'ENGINE': 'django.db.backends.postgresql',
>         [...]
>     },
>     'shifts_db': {
>         'ENGINE': 'djongo',
>         'ENFORCE_SCHEMA': False,
>         [...]
>     }
> }
> ```
> 
> It's been some time since I've done it so I don't remember exactly how I fixed this problem but disabling ENFORCE_SCHEMA may be enough.
> 
> Note that you can also log directly to your mongo db and add the required field to every documents. Then djongo will work again. I suppose ENFORCE_SCHEMA=True should fill these fields by itself but it doesn't seem to.
> 
> Anyway, disabling it looks like a good way but then you should frequently check that your docs contain the fields you are looking for (because they won't necessarily).

It's work for me too!
Thx ;)

**Comment by eswarsubra** [comment]
Thank you enderson. I am using MongoDB as backend and this doesnt seem to be fixed yet.
I have the same KeyError issue with Django 2.2.1 and MongoDB 4.2.1. 
Strange is that this attribute is totally optional so its normal that isnt present on all records.

Can anyone confirm please if this is fixed anf i am not enforcing the schema to go over this issue ?

Thanks

**Comment by TorhamDev** [comment]
Hi :)
thanks  @endersonmenezes  and @bachinblack, Your code saved me :)

if you use mongoDB you need add ENFORCE_SCHEMA like at this :
```
DATABASES = {
   'default': {
      'ENGINE' : 'djongo',
      'ENFORCE_SCHEMA': False,
       'NAME' : DB_NAME,
        'CLIENT': {
            'host': DB_HOST,
        }
   }
}
```
